### ISSUE TITLE
Resource Manager

### ISSUE THREAD

**Issue by kule** [theforeman/foreman_azure#4]
Are there any plans to update this for Azure RM?

I did start looking at this here but haven't been able to test it yet...https://github.com/kule/foreman_azure

**Comment by dLobatog** [comment]
No plans as of now but if you need it feel free to request here or in http://projects.theforeman.org/projects/azure/issues/new and at some point someone might take it over !

**Comment by dLobatog** [comment]
Now that https://github.com/fog/fog-azure-rm/ is out , I'll start using it, it's better maintained than regular fog-azure and it includes a module for networking that we need to keep improving the plugin
